### ISSUE TITLE
reshape problem

### ISSUE THREAD

**Issue by y-kl8** [XUSean0118/DVSNet#5]
I use python2.7, there still a error:

Traceback (most recent call last):
  File "inference.py", line 213, in <module>
    main()
  File "inference.py", line 124, in main
    pred_img = decode_labels(output, NUM_CLASSES)
  File "/home/yang/DVSNet-master/tools/img_utils.py", line 41, in decode_labels
    outputs = tf.cast(tf.reshape(outputs, (n, h, w, 3)), dtype=tf.uint8)
  File "/home/yang/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2451, in reshape
    name=name)
  File "/home/yang/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
    raise err
TypeError: Failed to convert object of type <type 'tuple'> to Tensor. Contents: (Dimension(1), Dimension(1024), Dimension(2048), 3). Consider casting elements to a supported type.

**Comment by XUSean0118** [comment]
Hi, y-kl8
Please try to use tensorflow-1.4.1 or rewrite some codes for new tensorflow version.
